version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: social_media_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpassword
      - POSTGRES_DB=social_media_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
