"""fix conversations last_message_id fk name

Revision ID: e5fe03f2ca0d
Revises: bc6717dff3bf
Create Date: 2026-08-10 18:29:01.314621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5fe03f2ca0d'
down_revision: Union[str, Sequence[str], None] = 'bc6717dff3bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_conversations_last_message_id_messages', 'conversations', type_='foreignkey')
    op.create_foreign_key('fk_conversations_last_message_id', 'conversations', 'messages', ['last_message_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_conversations_last_message_id', 'conversations', type_='foreignkey')
    op.create_foreign_key('fk_conversations_last_message_id_messages', 'conversations', 'messages', ['last_message_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
